spring:
  application:
    name: unbreja
  datasource:
    url: jdbc:postgresql://localhost:5440/unbreja
    username: postgres
    password: password
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true