version: "3"

services:
  db:
    container_name: unbreja-db
    image: bitnami/postgresql
    restart: always
    ports:
      - "5440:5432"
    environment:
        - POSTGRESQL_USERNAME=postgres
        - POSTGRESQL_PASSWORD=password
        - POSTGRESQL_DATABASE=unbreja